
# BUSA-523 — Homework 7: Pandas Basics  
**Student:** Hawa Kati Ido  
**Course:** Fall 2025 Business Analytics Programming (BUSA-523-01W-81E)  
**Files Used:** `Stocks.csv`, `Stock-Prices.csv`  
**Note:** `Symbol` is used as the index.

In [ ]:

import pandas as pd
from IPython.display import display

stocks_path = r"/mnt/data/Stocks.csv"
prices_path = r"/mnt/data/Stock-Prices.csv"

## LOAD

In [ ]:

# 1) Load data and use 'Symbol' as the index. Display the DataFrame.
df = pd.read_csv(stocks_path)
assert 'Symbol' in df.columns, "Expected 'Symbol' column in Stocks.csv"
df = df.set_index('Symbol', drop=True)
display(df)

,Company,Exchange,Industry,Date added,Notes,Index weighting
Symbol,,,,,,
MMM,3M,NYSE,Conglomerate,1976-08-09,As Minnesota Mining and Manufacturing,3.84%
AXP,American Express,NYSE,Financial services,1982-08-30,NaN,2.88%
AMGN,Amgen,NASDAQ,Pharmaceutical industry,2020-08-31,NaN,4.87%
AAPL,Apple Inc.,NASDAQ,Information technology,2015-03-19,NaN,2.57%
BA,Boeing,NYSE,Aerospace and defense,1987-03-12,NaN,4.92%
CAT,Caterpillar Inc.,NYSE,Construction and Mining,1991-05-06,NaN,4.54%
CVX,Chevron Corporation,NYSE,Petroleum industry,2008-02-19,Also 1930-07-18 to 1999-11-01,2.03%
CSCO,Cisco Systems,NASDAQ,Information technology,2009-06-08,NaN,1.00%
KO,The Coca-Cola Company,NYSE,Food industry,1987-03-12,Also 1932-05-26 to 1935-11-20,1.04%
DOW,Dow Inc.,NYSE,Chemical industry,2019-04-02,NaN,1.25%
GS,Goldman Sachs,NYSE,Financial services,2013-09-20,NaN,6.54%
HD,The Home Depot,NYSE,Retailing,1999-11-01,NaN,6.24%
HON,Honeywell,NASDAQ,Conglomerate,2020-08-31,NaN,4.47%
IBM,IBM,NYSE,Information technology,1979-06-29,Also 1932-05-26 to 1939-03-04,2.59%
INTC,Intel,NASDAQ,Information technology,1999-11-01,NaN,1.25%
JNJ,Johnson & Johnson,NYSE,Pharmaceutical industry,1997-03-17,NaN,3.12%
JPM,JPMorgan Chase,NYSE,Financial services,1991-05-06,NaN,2.95%
MCD,McDonald's,NYSE,Food industry,1985-10-30,NaN,4.49%
MRK,Merck & Co.,NYSE,Pharmaceutical industry,1979-06-29,NaN,1.49%
MSFT,Microsoft,NASDAQ,Information technology,1999-11-01,NaN,4.98%
NKE,"Nike, Inc.",NYSE,Apparel,2013-09-20,NaN,2.58%
PG,Procter & Gamble,NYSE,Fast-moving consumer goods,1932-05-26,NaN,2.64%
CRM,Salesforce,NYSE,Information technology,2020-08-31,NaN,4.45%
TRV,The Travelers Companies,NYSE,Financial services,2009-06-08,NaN,3.03%
UNH,UnitedHealth Group,NYSE,Managed health care,2012-09-24,NaN,7.33%
VZ,Verizon Communications,NYSE,Telecommunication,2004-04-08,NaN,1.13%
V,Visa Inc.,NYSE,Financial services,2013-09-20,NaN,4.33%
WBA,Walgreens Boots Alliance,NASDAQ,Retailing,2018-06-26,NaN,1.06%
WMT,Walmart,NYSE,Retailing,1997-03-17,NaN,2.72%
DIS,The Walt Disney Company,NYSE,Broadcasting and entertainment,1991-05-06,NaN,3.66%

In [ ]:

# 2) Show how many non-null values exist for each column and each column's dtype.
print("=== df.info() (non-null counts and dtypes) ===")
df.info()
print("\n=== Summary table (non-null_count + dtype) ===")
summary = pd.DataFrame({
    "non_null_count": df.notna().sum(),
    "dtype": df.dtypes.astype(str)
})
display(summary)

=== df.info() (non-null counts and dtypes) ===
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, MMM to DIS
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Company          30 non-null     object
 1   Exchange         30 non-null     object
 2   Industry         30 non-null     object
 3   Date added       30 non-null     object
 4   Notes            4 non-null      object
 5   Index weighting  30 non-null     object
dtypes: object(6)
memory usage: 1.6+ KB

=== Summary table (non-null_count + dtype) ===

                 non_null_count   dtype
Company                      30  object
Exchange                     30  object
Industry                     30  object
Date added                   30  object
Notes                         4  object
Index weighting              30  object

In [ ]:

# 3) Use shape and len() to find rows and columns.
rows, cols = df.shape
print(f"Rows: {rows}, Columns: {cols}, len(df): {len(df)}, len(df.columns): {len(df.columns)}")

Rows: 30, Columns: 6, len(df): 30, len(df.columns): 6

In [ ]:

# 4) Display the first and last 10 rows.
print("=== First 10 Rows ===")
display(df.head(10))
print("=== Last 10 Rows ===")
display(df.tail(10))

=== First 10 Rows ===

,Company,Exchange,Industry,Date added,Notes,Index weighting
Symbol,,,,,,
MMM,3M,NYSE,Conglomerate,1976-08-09,As Minnesota Mining and Manufacturing,3.84%
AXP,American Express,NYSE,Financial services,1982-08-30,NaN,2.88%
AMGN,Amgen,NASDAQ,Pharmaceutical industry,2020-08-31,NaN,4.87%
AAPL,Apple Inc.,NASDAQ,Information technology,2015-03-19,NaN,2.57%
BA,Boeing,NYSE,Aerospace and defense,1987-03-12,NaN,4.92%
CAT,Caterpillar Inc.,NYSE,Construction and Mining,1991-05-06,NaN,4.54%
CVX,Chevron Corporation,NYSE,Petroleum industry,2008-02-19,Also 1930-07-18 to 1999-11-01,2.03%
CSCO,Cisco Systems,NASDAQ,Information technology,2009-06-08,NaN,1.00%
KO,The Coca-Cola Company,NYSE,Food industry,1987-03-12,Also 1932-05-26 to 1935-11-20,1.04%
DOW,Dow Inc.,NYSE,Chemical industry,2019-04-02,NaN,1.25%

=== Last 10 Rows ===

,Company,Exchange,Industry,Date added,Notes,Index weighting
Symbol,,,,,,
NKE,"Nike, Inc.",NYSE,Apparel,2013-09-20,NaN,2.58%
PG,Procter & Gamble,NYSE,Fast-moving consumer goods,1932-05-26,NaN,2.64%
CRM,Salesforce,NYSE,Information technology,2020-08-31,NaN,4.45%
TRV,The Travelers Companies,NYSE,Financial services,2009-06-08,NaN,3.03%
UNH,UnitedHealth Group,NYSE,Managed health care,2012-09-24,NaN,7.33%
VZ,Verizon Communications,NYSE,Telecommunication,2004-04-08,NaN,1.13%
V,Visa Inc.,NYSE,Financial services,2013-09-20,NaN,4.33%
WBA,Walgreens Boots Alliance,NASDAQ,Retailing,2018-06-26,NaN,1.06%
WMT,Walmart,NYSE,Retailing,1997-03-17,NaN,2.72%
DIS,The Walt Disney Company,NYSE,Broadcasting and entertainment,1991-05-06,NaN,3.66%

## ACCESS

In [ ]:

# 5) Show the Company column.
display(df['Company'].to_frame())

                         Company
Symbol
MMM                           3M
AXP             American Express
AMGN                       Amgen
AAPL                  Apple Inc.
BA                        Boeing
CAT             Caterpillar Inc.
CVX          Chevron Corporation
CSCO               Cisco Systems
KO         The Coca-Cola Company
DOW                     Dow Inc.
GS                 Goldman Sachs
HD                The Home Depot
HON                    Honeywell
IBM                          IBM
INTC                       Intel
JNJ            Johnson & Johnson
JPM               JPMorgan Chase
MCD                   McDonald's
MRK                  Merck & Co.
MSFT                   Microsoft
NKE                   Nike, Inc.
PG              Procter & Gamble
CRM                   Salesforce
TRV      The Travelers Companies
UNH           UnitedHealth Group
VZ        Verizon Communications
V                      Visa Inc.
WBA     Walgreens Boots Alliance
WMT                      Walmart
DIS      The Walt Disney Company

In [ ]:

# 6) Show the columns named Company and Industry.
display(df[['Company', 'Industry']])

                         Company                        Industry
Symbol
MMM                           3M                    Conglomerate
AXP             American Express              Financial services
AMGN                       Amgen         Pharmaceutical industry
AAPL                  Apple Inc.          Information technology
BA                        Boeing           Aerospace and defense
CAT             Caterpillar Inc.         Construction and Mining
CVX          Chevron Corporation              Petroleum industry
CSCO               Cisco Systems          Information technology
KO         The Coca-Cola Company                   Food industry
DOW                     Dow Inc.               Chemical industry
GS                 Goldman Sachs              Financial services
HD                The Home Depot                       Retailing
HON                    Honeywell                    Conglomerate
IBM                          IBM          Information technology
INTC                       Intel          Information technology
JNJ            Johnson & Johnson         Pharmaceutical industry
JPM               JPMorgan Chase              Financial services
MCD                   McDonald's                   Food industry
MRK                  Merck & Co.         Pharmaceutical industry
MSFT                   Microsoft          Information technology
NKE                   Nike, Inc.                         Apparel
PG              Procter & Gamble      Fast-moving consumer goods
CRM                   Salesforce          Information technology
TRV      The Travelers Companies              Financial services
UNH           UnitedHealth Group             Managed health care
VZ        Verizon Communications               Telecommunication
V                      Visa Inc.              Financial services
WBA     Walgreens Boots Alliance                       Retailing
WMT                      Walmart                       Retailing
DIS      The Walt Disney Company  Broadcasting and entertainment

In [ ]:

# 7) Present the information for the row that has the symbol AAPL.
if 'AAPL' in df.index:
    display(df.loc[['AAPL']])
else:
    print("AAPL not found in index.")

,Company,Exchange,Industry,Date added,Notes,Index weighting
Symbol,,,,,,
AAPL,Apple Inc.,NASDAQ,Information technology,2015-03-19,NaN,2.57%

In [ ]:

# 8) Show the Exchange for the row with the Symbol AAPL.
if 'AAPL' in df.index and 'Exchange' in df.columns:
    print("Exchange for AAPL:", df.loc['AAPL', 'Exchange'])
elif 'AAPL' in df.index:
    print("Column 'Exchange' not found.")
else:
    print("AAPL not found in index.")

Exchange for AAPL: NASDAQ

## FILTER

In [ ]:

# 9) Sort (and show) the data by Industry, then Company.
sorted_df = df.sort_values(by=['Industry', 'Company'], ascending=[True, True], kind='mergesort')
display(sorted_df)

,Company,Exchange,Industry,Date added,Notes,Index weighting
Symbol,,,,,,
BA,Boeing,NYSE,Aerospace and defense,1987-03-12,NaN,4.92%
NKE,"Nike, Inc.",NYSE,Apparel,2013-09-20,NaN,2.58%
DIS,The Walt Disney Company,NYSE,Broadcasting and entertainment,1991-05-06,NaN,3.66%
DOW,Dow Inc.,NYSE,Chemical industry,2019-04-02,NaN,1.25%
MMM,3M,NYSE,Conglomerate,1976-08-09,As Minnesota Mining and Manufacturing,3.84%
HON,Honeywell,NASDAQ,Conglomerate,2020-08-31,NaN,4.47%
CAT,Caterpillar Inc.,NYSE,Construction and Mining,1991-05-06,NaN,4.54%
PG,Procter & Gamble,NYSE,Fast-moving consumer goods,1932-05-26,NaN,2.64%
AXP,American Express,NYSE,Financial services,1982-08-30,NaN,2.88%
GS,Goldman Sachs,NYSE,Financial services,2013-09-20,NaN,6.54%
JPM,JPMorgan Chase,NYSE,Financial services,1991-05-06,NaN,2.95%
TRV,The Travelers Companies,NYSE,Financial services,2009-06-08,NaN,3.03%
V,Visa Inc.,NYSE,Financial services,2013-09-20,NaN,4.33%
MCD,McDonald's,NYSE,Food industry,1985-10-30,NaN,4.49%
KO,The Coca-Cola Company,NYSE,Food industry,1987-03-12,Also 1932-05-26 to 1935-11-20,1.04%
AAPL,Apple Inc.,NASDAQ,Information technology,2015-03-19,NaN,2.57%
CSCO,Cisco Systems,NASDAQ,Information technology,2009-06-08,NaN,1.00%
IBM,IBM,NYSE,Information technology,1979-06-29,Also 1932-05-26 to 1939-03-04,2.59%
INTC,Intel,NASDAQ,Information technology,1999-11-01,NaN,1.25%
MSFT,Microsoft,NASDAQ,Information technology,1999-11-01,NaN,4.98%
CRM,Salesforce,NYSE,Information technology,2020-08-31,NaN,4.45%
UNH,UnitedHealth Group,NYSE,Managed health care,2012-09-24,NaN,7.33%
CVX,Chevron Corporation,NYSE,Petroleum industry,2008-02-19,Also 1930-07-18 to 1999-11-01,2.03%
AMGN,Amgen,NASDAQ,Pharmaceutical industry,2020-08-31,NaN,4.87%
JNJ,Johnson & Johnson,NYSE,Pharmaceutical industry,1997-03-17,NaN,3.12%
MRK,Merck & Co.,NYSE,Pharmaceutical industry,1979-06-29,NaN,1.49%
HD,The Home Depot,NYSE,Retailing,1999-11-01,NaN,6.24%
WBA,Walgreens Boots Alliance,NASDAQ,Retailing,2018-06-26,NaN,1.06%
WMT,Walmart,NYSE,Retailing,1997-03-17,NaN,2.72%
VZ,Verizon Communications,NYSE,Telecommunication,2004-04-08,NaN,1.13%

In [ ]:

# 10) Show the rows where Industry is Information Technology.
it_rows = df[df['Industry'] == 'Information Technology']
display(it_rows)

Empty DataFrame
Columns: [Company, Exchange, Industry, Date added, Notes, Index weighting]
Index: []

## MISSING

In [ ]:

# 11) Show the rows where Notes has a value (not missing/empty).
if 'Notes' in df.columns:
    notes_present = df[df['Notes'].notna() & (df['Notes'].astype(str).str.strip() != "")]
    display(notes_present)
else:
    print("Column 'Notes' not found in Stocks.csv.")

,Company,Exchange,Industry,Date added,Notes,Index weighting
Symbol,,,,,,
MMM,3M,NYSE,Conglomerate,1976-08-09,As Minnesota Mining and Manufacturing,3.84%
CVX,Chevron Corporation,NYSE,Petroleum industry,2008-02-19,Also 1930-07-18 to 1999-11-01,2.03%
KO,The Coca-Cola Company,NYSE,Food industry,1987-03-12,Also 1932-05-26 to 1935-11-20,1.04%
IBM,IBM,NYSE,Information technology,1979-06-29,Also 1932-05-26 to 1939-03-04,2.59%

## DROPPING

In [ ]:

# 12) Create and display a DataFrame excluding the Notes column.
if 'Notes' in df.columns:
    df_no_notes = df.drop(columns=['Notes'])
    display(df_no_notes)
else:
    df_no_notes = df.copy()
    print("Column 'Notes' not present; df_no_notes equals df.")

,Company,Exchange,Industry,Date added,Index weighting
Symbol,,,,,
MMM,3M,NYSE,Conglomerate,1976-08-09,3.84%
AXP,American Express,NYSE,Financial services,1982-08-30,2.88%
AMGN,Amgen,NASDAQ,Pharmaceutical industry,2020-08-31,4.87%
AAPL,Apple Inc.,NASDAQ,Information technology,2015-03-19,2.57%
BA,Boeing,NYSE,Aerospace and defense,1987-03-12,4.92%
CAT,Caterpillar Inc.,NYSE,Construction and Mining,1991-05-06,4.54%
CVX,Chevron Corporation,NYSE,Petroleum industry,2008-02-19,2.03%
CSCO,Cisco Systems,NASDAQ,Information technology,2009-06-08,1.00%
KO,The Coca-Cola Company,NYSE,Food industry,1987-03-12,1.04%
DOW,Dow Inc.,NYSE,Chemical industry,2019-04-02,1.25%
GS,Goldman Sachs,NYSE,Financial services,2013-09-20,6.54%
HD,The Home Depot,NYSE,Retailing,1999-11-01,6.24%
HON,Honeywell,NASDAQ,Conglomerate,2020-08-31,4.47%
IBM,IBM,NYSE,Information technology,1979-06-29,2.59%
INTC,Intel,NASDAQ,Information technology,1999-11-01,1.25%
JNJ,Johnson & Johnson,NYSE,Pharmaceutical industry,1997-03-17,3.12%
JPM,JPMorgan Chase,NYSE,Financial services,1991-05-06,2.95%
MCD,McDonald's,NYSE,Food industry,1985-10-30,4.49%
MRK,Merck & Co.,NYSE,Pharmaceutical industry,1979-06-29,1.49%
MSFT,Microsoft,NASDAQ,Information technology,1999-11-01,4.98%
NKE,"Nike, Inc.",NYSE,Apparel,2013-09-20,2.58%
PG,Procter & Gamble,NYSE,Fast-moving consumer goods,1932-05-26,2.64%
CRM,Salesforce,NYSE,Information technology,2020-08-31,4.45%
TRV,The Travelers Companies,NYSE,Financial services,2009-06-08,3.03%
UNH,UnitedHealth Group,NYSE,Managed health care,2012-09-24,7.33%
VZ,Verizon Communications,NYSE,Telecommunication,2004-04-08,1.13%
V,Visa Inc.,NYSE,Financial services,2013-09-20,4.33%
WBA,Walgreens Boots Alliance,NASDAQ,Retailing,2018-06-26,1.06%
WMT,Walmart,NYSE,Retailing,1997-03-17,2.72%
DIS,The Walt Disney Company,NYSE,Broadcasting and entertainment,1991-05-06,3.66%

## JOIN

In [ ]:

# 13) Join with Stock-Prices.csv (Symbol, Price) using join()
prices = pd.read_csv(prices_path)
assert 'Symbol' in prices.columns and 'Price' in prices.columns, "Expected 'Symbol' and 'Price' in Stock-Prices.csv"
prices = prices.set_index('Symbol', drop=True)
df_with_prices = df.join(prices[['Price']], how='left')
display(df_with_prices)

# Save the joined output for submission
output_path = "/mnt/data/Stocks_with_Prices.csv"
df_with_prices.to_csv(output_path, index=True)
print("Saved:", output_path)

,Company,Exchange,Industry,Date added,Notes,Index weighting,Price
Symbol,,,,,,,
MMM,3M,NYSE,Conglomerate,1976-08-09,As Minnesota Mining and Manufacturing,3.84%,223.34
AXP,American Express,NYSE,Financial services,1982-08-30,NaN,2.88%,176.22
AMGN,Amgen,NASDAQ,Pharmaceutical industry,2020-08-31,NaN,4.87%,262.12
AAPL,Apple Inc.,NASDAQ,Information technology,2015-03-19,NaN,2.57%,137.07
BA,Boeing,NYSE,Aerospace and defense,1987-03-12,NaN,4.92%,271.76
CAT,Caterpillar Inc.,NYSE,Construction and Mining,1991-05-06,NaN,4.54%,265.12
CVX,Chevron Corporation,NYSE,Petroleum industry,2008-02-19,Also 1930-07-18 to 1999-11-01,2.03%,114.33
CSCO,Cisco Systems,NASDAQ,Information technology,2009-06-08,NaN,1.00%,58.23
KO,The Coca-Cola Company,NYSE,Food industry,1987-03-12,Also 1932-05-26 to 1935-11-20,1.04%,60.89
DOW,Dow Inc.,NYSE,Chemical industry,2019-04-02,NaN,1.25%,75.30
GS,Goldman Sachs,NYSE,Financial services,2013-09-20,NaN,6.54%,409.46
HD,The Home Depot,NYSE,Retailing,1999-11-01,NaN,6.24%,350.93
HON,Honeywell,NASDAQ,Conglomerate,2020-08-31,NaN,4.47%,254.53
IBM,IBM,NYSE,Information technology,1979-06-29,Also 1932-05-26 to 1939-03-04,2.59%,158.39
INTC,Intel,NASDAQ,Information technology,1999-11-01,NaN,1.25%,62.89
JNJ,Johnson & Johnson,NYSE,Pharmaceutical industry,1997-03-17,NaN,3.12%,186.34
JPM,JPMorgan Chase,NYSE,Financial services,1991-05-06,NaN,2.95%,180.62
MCD,McDonald's,NYSE,Food industry,1985-10-30,NaN,4.49%,257.24
MRK,Merck & Co.,NYSE,Pharmaceutical industry,1979-06-29,NaN,1.49%,14.08
MSFT,Microsoft,NASDAQ,Information technology,1999-11-01,NaN,4.98%,274.81
NKE,"Nike, Inc.",NYSE,Apparel,2013-09-20,NaN,2.58%,150.11
PG,Procter & Gamble,NYSE,Fast-moving consumer goods,1932-05-26,NaN,2.64%,148.39
CRM,Salesforce,NYSE,Information technology,2020-08-31,NaN,4.45%,261.25
TRV,The Travelers Companies,NYSE,Financial services,2009-06-08,NaN,3.03%,175.67
UNH,UnitedHealth Group,NYSE,Managed health care,2012-09-24,NaN,7.33%,453.73
VZ,Verizon Communications,NYSE,Telecommunication,2004-04-08,NaN,1.13%,62.15
V,Visa Inc.,NYSE,Financial services,2013-09-20,NaN,4.33%,250.25
WBA,Walgreens Boots Alliance,NASDAQ,Retailing,2018-06-26,NaN,1.06%,58.03
WMT,Walmart,NYSE,Retailing,1997-03-17,NaN,2.72%,156.22
DIS,The Walt Disney Company,NYSE,Broadcasting and entertainment,1991-05-06,NaN,3.66%,196.66

Saved: /mnt/data/Stocks_with_Prices.csv